In [2]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 4.7 MB 9.3 MB/s 
     |████████████████████████████████| 6.6 MB 46.7 MB/s 
     |████████████████████████████████| 120 kB 63.6 MB/s 


In [3]:
!pip install datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 365 kB 9.3 MB/s 
     |████████████████████████████████| 115 kB 22.1 MB/s 
     |████████████████████████████████| 212 kB 29.6 MB/s 
     |████████████████████████████████| 127 kB 28.2 MB/s 
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3


In [4]:
import transformers
from transformers import pipeline


In [ ]:
ner=pipeline(model="Davlan/bert-base-multilingual-cased-ner-hrl")

Downloading:   0%|          | 0.00/1.30k [00:00<?, ?B/s]

In [ ]:
ner("Creo que Madonna es tan chévere como el Quijote")

[{'entity': 'B-PER',
  'score': 0.9998497,
  'index': 4,
  'word': 'Madonna',
  'start': 9,
  'end': 16},
 {'entity': 'B-PER',
  'score': 0.70504665,
  'index': 12,
  'word': 'Qui',
  'start': 40,
  'end': 43},
 {'entity': 'I-PER',
  'score': 0.97654825,
  'index': 13,
  'word': '##jot',
  'start': 43,
  'end': 46},
 {'entity': 'I-PER',
  'score': 0.925881,
  'index': 14,
  'word': '##e',
  'start': 46,
  'end': 47}]

In [ ]:

classifier = pipeline('sentiment-analysis')

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


In [ ]:
 classifier('Why the hell do we need to always work in english?')

[{'label': 'NEGATIVE', 'score': 0.9997010827064514}]

In [ ]:
 classifier('It is a good time to start a business')

[{'label': 'POSITIVE', 'score': 0.999862551689148}]

In [ ]:
 classifier('I did my homework')

[{'label': 'POSITIVE', 'score': 0.985089123249054}]

In [ ]:
anonimo = pipeline('sentiment-analysis', model="finiteautomata/beto-sentiment-analysis")

In [ ]:
positivo=["Todos los profesores son unos ángeles. Gracias por tanto","intento estar tranquilo en momentos dificiles. Nada como una michelada y un ceviche",
          "actitud positiva!!",
          "Hoy es un dia muy feliz porque estoy aprediendo nuevos conceptos con estas ponencias",
          "la clase está muy interesante"]
negativo=["todos los políticos son unos corruptos" ,"A veces ni se cómo es que después de este año sigo vivo",
          "Solo sé que nada sé",
          "esta situación es poco agradable",
          "Hoy me fue mal en el trabajo :("]
varios=["Estoy en esa y le saqué un yogurt a mi sobrinito, lo estoy disfrutando con culpa","el cambio empieza en ti"]
neutros=["hola","adiós","El alfarero habló de su trabajo", "Hagamos nuestro el mundo"]

In [ ]:
anonimo(positivo)

[{'label': 'POS', 'score': 0.9986187219619751},
 {'label': 'POS', 'score': 0.5033699870109558},
 {'label': 'POS', 'score': 0.9980581402778625},
 {'label': 'POS', 'score': 0.998663067817688},
 {'label': 'POS', 'score': 0.9988127946853638}]

In [ ]:
anonimo(negativo)

[{'label': 'NEG', 'score': 0.999213457107544},
 {'label': 'NEU', 'score': 0.6017295122146606},
 {'label': 'NEU', 'score': 0.74541175365448},
 {'label': 'NEG', 'score': 0.999332845211029},
 {'label': 'NEG', 'score': 0.9994254112243652}]

In [ ]:
anonimo(varios)

[{'label': 'POS', 'score': 0.9986978769302368},
 {'label': 'NEU', 'score': 0.8625587224960327}]

In [ ]:
anonimo(neutros)

[{'label': 'NEU', 'score': 0.9820472002029419},
 {'label': 'NEU', 'score': 0.6655517816543579},
 {'label': 'NEU', 'score': 0.9976934790611267},
 {'label': 'POS', 'score': 0.9093490839004517}]

In [ ]:
bert_español = pipeline('sentiment-analysis', model="nlptown/bert-base-multilingual-uncased-sentiment")

In [ ]:
bert_español(positivo)

[{'label': '5 stars', 'score': 0.5416910648345947},
 {'label': '2 stars', 'score': 0.3716343939304352},
 {'label': '5 stars', 'score': 0.46921542286872864},
 {'label': '5 stars', 'score': 0.6852555871009827},
 {'label': '4 stars', 'score': 0.48274141550064087}]

In [ ]:
bert_español(negativo)

[{'label': '1 star', 'score': 0.6841945648193359},
 {'label': '3 stars', 'score': 0.28943851590156555},
 {'label': '1 star', 'score': 0.34308701753616333},
 {'label': '2 stars', 'score': 0.5511031150817871},
 {'label': '2 stars', 'score': 0.4360465705394745}]

In [ ]:
bert_español(neutros)

[{'label': '3 stars', 'score': 0.25504207611083984},
 {'label': '5 stars', 'score': 0.43525704741477966},
 {'label': '4 stars', 'score': 0.3598667085170746},
 {'label': '5 stars', 'score': 0.6405256986618042}]

In [ ]:
bert_español(varios)

[{'label': '1 star', 'score': 0.43304044008255005},
 {'label': '5 stars', 'score': 0.23197481036186218}]

In [ ]:
sintaxis=["Eran un buen amiga", 
          "Juana se despertó en la mañana radiante",
          "Juana, radiante, se despertó en la mañana", 
          "Era una mañana radiante. Juana se despertó"]
anonimo(sintaxis)

[{'label': 'POS', 'score': 0.9983212351799011},
 {'label': 'NEU', 'score': 0.9981732368469238},
 {'label': 'NEU', 'score': 0.9177748560905457},
 {'label': 'POS', 'score': 0.9323041439056396}]

In [ ]:
bert_español(sintaxis)

[{'label': '4 stars', 'score': 0.3815363049507141},
 {'label': '1 star', 'score': 0.423431396484375},
 {'label': '1 star', 'score': 0.27434954047203064},
 {'label': '1 star', 'score': 0.4494757354259491}]

In [ ]:
composicional=["el perro se comió la cena de mi hermano", 
               "mi hermano se comió la cena del perro",
               "Fue consumida la comida de mi hermano por el perro", 
               "uno se comió la cena del otro"]
anonimo(composicional)

[{'label': 'NEG', 'score': 0.9963091015815735},
 {'label': 'NEG', 'score': 0.773880124092102},
 {'label': 'NEG', 'score': 0.9920247793197632},
 {'label': 'NEU', 'score': 0.7047760486602783}]

In [ ]:
bert_español(composicional)

[{'label': '1 star', 'score': 0.26040685176849365},
 {'label': '5 stars', 'score': 0.28950628638267517},
 {'label': '1 star', 'score': 0.5374513864517212},
 {'label': '1 star', 'score': 0.46615809202194214}]

In [ ]:
conocimiento=["la experiencia fue larga","la noche entre los dos fue larga","la fila del banco fue larga"]
anonimo(conocimiento)

[{'label': 'NEU', 'score': 0.9977995753288269},
 {'label': 'NEU', 'score': 0.9476736187934875},
 {'label': 'NEU', 'score': 0.9979217648506165}]

In [ ]:
bert_español(conocimiento)

[{'label': '3 stars', 'score': 0.30843260884284973},
 {'label': '2 stars', 'score': 0.3988797664642334},
 {'label': '2 stars', 'score': 0.4060215353965759}]

In [ ]:
polisemia=["era muy ligera", "la cámara era muy ligera", "la película era muy ligera"]
anonimo(polisemia)

[{'label': 'NEG', 'score': 0.8467423915863037},
 {'label': 'NEU', 'score': 0.5374398827552795},
 {'label': 'NEG', 'score': 0.9337968230247498}]

In [ ]:
bert_español(polisemia)

[{'label': '2 stars', 'score': 0.3181767463684082},
 {'label': '2 stars', 'score': 0.3792048394680023},
 {'label': '2 stars', 'score': 0.3407782316207886}]

In [ ]:
anafora=["hacia rato no recibía uno de estos",
         "Recibí un puño. Hacia rato no recibía uno de estos" , 
         "Recibí un regalo. Hacia rato no recibía uno de estos"]
anonimo(anafora)

[{'label': 'NEG', 'score': 0.9980902075767517},
 {'label': 'NEG', 'score': 0.9992528557777405},
 {'label': 'NEU', 'score': 0.7495959401130676}]

In [ ]:
bert_español(anafora)

[{'label': '1 star', 'score': 0.6497986316680908},
 {'label': '1 star', 'score': 0.7433289885520935},
 {'label': '1 star', 'score': 0.6056777238845825}]

In [ ]:
pragmatica=["La batería es perfecta para ahorrar pues alcanza para una sola llamada",
            "Todos los políticos del país son unos ángeles", 
            "qué malo haber recibido tanta plata por mi trabajo"]
anonimo(pragmatica)

[{'label': 'POS', 'score': 0.8472196459770203},
 {'label': 'NEG', 'score': 0.9888207912445068},
 {'label': 'NEG', 'score': 0.9992914199829102}]

In [ ]:
bert_español(pragmatica)

[{'label': '5 stars', 'score': 0.6421207189559937},
 {'label': '5 stars', 'score': 0.3224475681781769},
 {'label': '1 star', 'score': 0.7030344605445862}]

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving tass14neg.txt to tass14neg.txt
Saving tass14pos.txt to tass14pos.txt


In [5]:
positivo=[]
with open("tass14pos.txt", encoding="latin-1") as f:
    for line in f:
        positivo.append(line)
len(positivo)

negativo=[]
with open("tass14neg.txt", encoding="latin-1") as f:
    for line in f:
        negativo.append(line)
len(negativo)

total=positivo + negativo
len(total)


4300

In [6]:
respuesta=[1]*len(positivo)+ [0]*len(negativo)
len(respuesta)


4300

##Pasos de trabajo
Con una muestra, vamos a explicar un poco el proceso realizado por un transformer. Primero sacamos la muestra.

In [7]:
import random
tassprueba=random.sample(positivo,100)+random.sample(negativo,100)


Luego mostraremos las etapas: tokenización, generación de representación y adaptación a la tarea

In [8]:
from transformers import AutoTokenizer
modelo="dccuchile/bert-base-spanish-wwm-cased"
modelo2="nlptown/bert-base-multilingual-uncased-sentiment"
tokenizado = AutoTokenizer.from_pretrained(modelo)

Ahora tokenicemos. Miremos que hace el tokenizador

In [11]:
verlotok=tokenizado.tokenize("Esta es la prueba definitiva de lo mucho que te quiero")
print(verlotok)

['Esta', 'es', 'la', 'prueba', 'definitiva', 'de', 'lo', 'mucho', 'que', 'te', 'quiero']


In [9]:
tokenizadobert = AutoTokenizer.from_pretrained(modelo2)
verlotokbert=tokenizadobert.tokenize("Esta es la prueba definitiva de lo mucho que te quiero")
verlotokbert

['esta',
 'es',
 'la',
 'prueba',
 'definitiva',
 'de',
 'lo',
 'mucho',
 'que',
 'te',
 'quiero']

In [12]:
vernum=tokenizado.convert_tokens_to_ids(verlotok)
print(vernum)

[1949, 1058, 1030, 3889, 8988, 1008, 1114, 1789, 1038, 1240, 1937]


Ahora tokenizamos y convertimos nuestros tokenes a tensores (matrices de números). También creamos la capa de atención.
Obsérvese que tenemos que reemplazar con tokenes vacíos cuando las longitudes son diferentes (padding) y evitar que sean más largas de lo que el transformer puede aguantar (truncation)

In [ ]:
entradas = tokenizado(tassprueba, padding=True, truncation=True, return_tensors="tf")
print(entradas)

{'input_ids': <tf.Tensor: shape=(200, 103), dtype=int32, numpy=
array([[    4, 19832,   977, ...,     1,     1,     1],
       [    4,  1094,   977, ...,     1,     1,     1],
       [    4, 20493, 11083, ...,     1,     1,     1],
       ...,
       [    4,  1164,  3253, ...,     1,     1,     1],
       [    4, 29262, 19249, ...,     1,     1,     1],
       [    4,  1162, 13882, ...,     1,     1,     1]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(200, 103), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(200, 103), dtype=int32, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=int32

Ahora cargamos el modelo. Modelo no está hecho para predecir sentimiento, por eso nos va a fallar, pero luego vamos a sintonizarlo en fino.

In [ ]:
from transformers import TFAutoModel

model = TFAutoModel.from_pretrained(modelo)

Some layers from the model checkpoint at dccuchile/bert-base-spanish-wwm-cased were not used when initializing TFBertModel: ['mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFBertModel were not initialized from the model checkpoint at dccuchile/bert-base-spanish-wwm-cased and are newly initialized: ['bert/pooler/dense/bias:0', 'bert/pooler/dense/kernel:0']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Veamos el tamaño de nuestros tensores en la salida de nuestro modelo. Nos está entregando las capas ocultas (la representación)

In [ ]:
salida=model(entradas)
print(salida.last_hidden_state.shape)

(200, 103, 768)


Ahora importamos el modelo como si fuese para clasificar

In [ ]:
from transformers import TFAutoModelForSequenceClassification

modelsentiment = TFAutoModelForSequenceClassification.from_pretrained(modelo)
salidasent = modelsentiment(entradas)

All model checkpoint layers were used when initializing TFBertForSequenceClassification.

Some layers of TFBertForSequenceClassification were not initialized from the model checkpoint at dccuchile/bert-base-spanish-wwm-cased and are newly initialized: ['classifier', 'bert/pooler/dense/bias:0', 'bert/pooler/dense/kernel:0']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Ahora si, solo tenemos los logits

In [ ]:
print(salidasent.logits.shape)

(200, 2)


In [ ]:
print(salidasent.logits)

tf.Tensor(
[[ 0.01677968 -0.21495423]
 [ 0.20230621  0.01936617]
 [ 0.12024184  0.00722105]
 [ 0.11159766 -0.00160944]
 [ 0.18364033  0.03226954]
 [ 0.10493656  0.07253446]
 [ 0.1469506  -0.10242134]
 [ 0.06929553  0.07982028]
 [ 0.1555504  -0.00613449]
 [ 0.03580266  0.04785827]
 [ 0.18665522  0.06828783]
 [-0.01324251 -0.04621393]
 [ 0.03568145  0.01771207]
 [ 0.08435615 -0.04050758]
 [ 0.14941788  0.07617063]
 [ 0.1284799   0.02121752]
 [ 0.1039857   0.10074428]
 [ 0.17078009  0.14017133]
 [ 0.16044901  0.12656516]
 [ 0.03172185  0.08475606]
 [-0.02098785  0.03590906]
 [ 0.09293492  0.01968452]
 [ 0.16397479  0.11848839]
 [ 0.02357397  0.05109425]
 [ 0.13634732 -0.04323883]
 [ 0.05534959  0.02526039]
 [ 0.12522879  0.04614624]
 [ 0.19091566  0.09994609]
 [ 0.00997694 -0.1136267 ]
 [ 0.04449067  0.06288286]
 [-0.07613919 -0.09385569]
 [ 0.12238642  0.09897345]
 [ 0.0400206  -0.02025863]
 [ 0.18113497  0.08106606]
 [ 0.06413132  0.07729361]
 [ 0.14534596  0.08053286]
 [ 0.16334617  0.

Como no hay etiquetas configuradas, el las marca como 0 y 1.

In [ ]:
modelsentiment.config.id2label

{0: 'LABEL_0', 1: 'LABEL_1'}

Aqui entonces las volvemos probabilidades

In [ ]:
import tensorflow as tf

prediccionproceso = tf.math.softmax(salidasent.logits, axis=-1)
print(prediccionproceso)

tf.Tensor(
[[0.5576756  0.4423244 ]
 [0.54560786 0.45439214]
 [0.5282252  0.47177488]
 [0.52827156 0.47172838]
 [0.53777057 0.46222937]
 [0.5080998  0.49190018]
 [0.5620219  0.4379781 ]
 [0.49736887 0.5026312 ]
 [0.5403334  0.4596666 ]
 [0.4969861  0.50301385]
 [0.52955735 0.47044265]
 [0.5082421  0.49175784]
 [0.5044922  0.4955078 ]
 [0.53117543 0.46882457]
 [0.51830363 0.48169637]
 [0.5267899  0.4732101 ]
 [0.5008103  0.49918962]
 [0.50765157 0.49234837]
 [0.5084702  0.49152985]
 [0.48674452 0.5132554 ]
 [0.4857796  0.5142204 ]
 [0.5183044  0.48169556]
 [0.51136965 0.48863038]
 [0.4931204  0.5068797 ]
 [0.54477626 0.4552237 ]
 [0.50752175 0.49247828]
 [0.5197603  0.48023963]
 [0.5227267  0.4772733 ]
 [0.5308616  0.46913835]
 [0.49540204 0.5045979 ]
 [0.504429   0.49557093]
 [0.50585294 0.494147  ]
 [0.51506525 0.48493475]
 [0.5249964  0.47500363]
 [0.49670947 0.50329053]
 [0.5161976  0.4838024 ]
 [0.5357796  0.4642204 ]
 [0.53559995 0.46440008]
 [0.5352919  0.4647081 ]
 [0.54742795 0

In [ ]:
type(prediccionproceso)

tensorflow.python.framework.ops.EagerTensor

##Sintonizado fino de modelos
Ahora vamos a hacer la sintonización fina de un modelo de lenguaje natural a nuestra tarea de análisis de sentimiento. Empezamos por crear el dataset

Aqui creamos el dataset

In [14]:
import pandas as pd
d = {'texto':total,'label':respuesta}
textobase=pd.DataFrame(d)
textobase.head(5)


texto  label
0                        @marodriguezb Gracias MAR\n      1
1  Conozco a alguien q es adicto al drama! Ja ja ...      1
2  Toca @crackoviadeTV3 . Grabación dl especial N...      1
3  Buen día todos! Lo primero mandar un abrazo gr...      1
4  Desde el escaño. Todo listo para empezar #endi...      1

In [15]:
textobase["label"].value_counts()

1    2709
0    1591
Name: label, dtype: int64

Primero con Pandas separamos la base de test. Luego, con ayuda de la librería datasets dividimos el entrenamiento en train y validation. Cmo vemos se convierte en un tipo de objetos Diccionario de datasets

In [16]:
from sklearn.model_selection import train_test_split
textobase_tr, textobase_test = train_test_split(textobase, test_size=0.1, random_state=88, stratify=respuesta)

In [17]:
import datasets
from datasets import Dataset
basetot=Dataset.from_pandas(textobase_tr)
nuevo=basetot.train_test_split(test_size=0.2)
nuevo["train"].features

{'texto': Value(dtype='string', id=None),
 'label': Value(dtype='int64', id=None),
 '__index_level_0__': Value(dtype='int64', id=None)}

In [18]:
nuevo["test"].features

{'texto': Value(dtype='string', id=None),
 'label': Value(dtype='int64', id=None),
 '__index_level_0__': Value(dtype='int64', id=None)}

In [19]:
nuevo

DatasetDict({
    train: Dataset({
        features: ['texto', 'label', '__index_level_0__'],
        num_rows: 3096
    })
    test: Dataset({
        features: ['texto', 'label', '__index_level_0__'],
        num_rows: 774
    })
})

In [20]:
basetot.features

{'texto': Value(dtype='string', id=None),
 'label': Value(dtype='int64', id=None),
 '__index_level_0__': Value(dtype='int64', id=None)}

In [21]:
from transformers import AutoModel, AutoTokenizer, BertTokenizer,AutoModelForSequenceClassification

Creamos los tensores de nuestro modelo, haciendo el padding.

In [37]:
tokenizado2=AutoTokenizer.from_pretrained(modelo, padding=True, return_tensors="tf")


Creamos una función para el truncado

In [38]:
def tokenize_nuevo(base):
    return tokenizado2(base["texto"], padding="max_length",truncation=True)
    #return tokenizado2(base["texto"])

Y la ejecutamos

In [39]:
nuevo_tokenizado=nuevo.map(tokenize_nuevo,batched=True,)

  0%|          | 0/4 [00:00<?, ?ba/s]

  0%|          | 0/1 [00:00<?, ?ba/s]

Y ya aquí creamos los datasets de tensorflow que nos servirán para el entrenamiento

In [40]:
nuevo_tokenizado["train"].data

InMemoryTable
texto: string
label: int64
__index_level_0__: int64
input_ids: list<item: int32>
  child 0, item: int32
token_type_ids: list<item: int8>
  child 0, item: int8
attention_mask: list<item: int8>
  child 0, item: int8
----
texto: [["El recuerdo de Rafael León queda entre nosotros. Su labor poética, sus cuidadas ediciones, su impulso a la cultura en Màlaga no se olvidaràn
","182735296906002433;;;DavilaGaceta;;;2012-03-22T08:43:16;;;política;;;N;;;AGREEMENT;;;La gente está sobrecogidahttp://t.co/cGVyaibU
","160492708878745600;;;AlejandroSanz;;;2012-01-20T23:43:38;;;música;;;P;;;AGREEMENT;;;Si tambien tengo. Voy a mandar foto RT @bbreso: @AlejandroSanz @sanzfusion ese es un buen piano, (cont) http://t.co/9BM2oHfE
","#martesy13 bicicletas sin sillín PN!!
","El empeñodedosmujeres hace de Holiday World una empresa familiarmente responsable. http://t.co/rfogRans
","Garzón, hoy en el banquillo por las escuchas a abogados de Gürtel ¿Creéis que será condenado?
","153250422600114176;;;P

In [41]:
tensores_train= nuevo_tokenizado["train"].to_tf_dataset(
    columns=["attention_mask", "input_ids", "token_type_ids"],
    label_cols=["label"],
    shuffle=True,
     batch_size=32)

tensores_test= nuevo_tokenizado["test"].to_tf_dataset(
    columns=["attention_mask", "input_ids", "token_type_ids"],
    label_cols=["label"],
    shuffle=True,
     batch_size=32)

In [42]:
tensores_test

<PrefetchDataset element_spec=({'input_ids': TensorSpec(shape=(None, 512), dtype=tf.int64, name=None), 'token_type_ids': TensorSpec(shape=(None, 512), dtype=tf.int64, name=None), 'attention_mask': TensorSpec(shape=(None, 512), dtype=tf.int64, name=None)}, TensorSpec(shape=(None,), dtype=tf.int64, name=None))>

Cargamos el modelo como uno de clasificación

In [35]:
from transformers import TFAutoModelForSequenceClassification
from transformers import TFAutoModelForCausalLM


modelado = TFAutoModelForSequenceClassification.from_pretrained(modelo, num_labels=2)

All model checkpoint layers were used when initializing TFBertForSequenceClassification.

Some layers of TFBertForSequenceClassification were not initialized from the model checkpoint at dccuchile/bert-base-spanish-wwm-cased and are newly initialized: ['classifier', 'bert/pooler/dense/bias:0', 'bert/pooler/dense/kernel:0']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Y finalmente lo entrenamos de acuerdo a lo que necesitemos. 

In [36]:
class_weight = {0: 3.,
                1: 2.}

In [ ]:
from tensorflow.keras.losses import SparseCategoricalCrossentropy

modelado.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=5e-5),
    loss=SparseCategoricalCrossentropy(from_logits=True),
    metrics=["accuracy"],
)
modelado.fit(
    tensores_train,
    validation_data=tensores_test,class_weight=class_weight
)

102/102 [==============================] - 3449s 34s/step - loss: 1.3803 - accuracy: 0.7059 - val_loss: 0.5318 - val_accuracy: 0.7500


In [ ]:
predicciones = modelado.predict(tensores_test)["logits"]


In [ ]:
display(predicciones)

array([[-0.9857655 ,  1.2106272 ],
       [-0.49818602,  0.710643  ],
       [ 0.12088899, -0.01653264],
       ...,
       [-0.16424346,  0.2235637 ],
       [-0.23815614,  0.30663204],
       [ 1.4339411 , -0.8268182 ]], dtype=float32)

In [ ]:
import numpy as np
clase_predicha = np.argmax(predicciones, axis=1)
print(predicciones.shape, clase_predicha.shape)

(800, 2) (800,)


In [ ]:
clase_predicha

array([1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,

In [ ]:
import sklearn
from sklearn.metrics import precision_recall_curve, roc_curve, balanced_accuracy_score, f1_score, precision_score,recall_score, roc_auc_score



Aqui al final al parecer 17 tuits no tuvieron representación. Por eso toca recortar a 800

In [ ]:
transprec=sklearn.metrics.precision_score(nuevo["test"]["label"][0:800],clase_predicha)
transrecall=sklearn.metrics.recall_score(nuevo["test"]["label"][0:800],clase_predicha)
transfscore=sklearn.metrics.f1_score(nuevo["test"]["label"][0:800],clase_predicha)
transauc=sklearn.metrics.roc_auc_score(nuevo["test"]["label"][0:800],clase_predicha)
print(transprec,transrecall,transfscore,transauc)

0.6247933884297521 0.7636363636363637 0.6872727272727273 0.5096870342771982


##Uso de otros pipelines para diferentes tareas

In [43]:
ner=pipeline(model="Davlan/bert-base-multilingual-cased-ner-hrl")

Downloading:   0%|          | 0.00/1.30k [00:00<?, ?B/s]

In [44]:
ner("Creo que Madonna es tan chévere como el Quijote")

[{'entity': 'B-PER',
  'score': 0.9998497,
  'index': 4,
  'word': 'Madonna',
  'start': 9,
  'end': 16},
 {'entity': 'B-PER',
  'score': 0.7050461,
  'index': 12,
  'word': 'Qui',
  'start': 40,
  'end': 43},
 {'entity': 'I-PER',
  'score': 0.97654825,
  'index': 13,
  'word': '##jot',
  'start': 43,
  'end': 46},
 {'entity': 'I-PER',
  'score': 0.9258813,
  'index': 14,
  'word': '##e',
  'start': 46,
  'end': 47}]

In [45]:
llenar=pipeline(model="xlm-roberta-base")

Downloading:   0%|          | 0.00/1.86k [00:00<?, ?B/s]

In [46]:
llenar("Rey es a hombre como reina es a <mask>")

[{'score': 0.5341500043869019,
  'token': 44543,
  'token_str': 'mujer',
  'sequence': 'Rey es a hombre como reina es a mujer'},
 {'score': 0.06330035626888275,
  'token': 45752,
  'token_str': 'rey',
  'sequence': 'Rey es a hombre como reina es a rey'},
 {'score': 0.0513906292617321,
  'token': 39574,
  'token_str': 'Dios',
  'sequence': 'Rey es a hombre como reina es a Dios'},
 {'score': 0.021211052313447,
  'token': 75371,
  'token_str': 'tierra',
  'sequence': 'Rey es a hombre como reina es a tierra'},
 {'score': 0.015028557740151882,
  'token': 37208,
  'token_str': 'madre',
  'sequence': 'Rey es a hombre como reina es a madre'}]

In [50]:
llenar("Yo tengo un <mask> que me ama")

[{'score': 0.2145082801580429,
  'token': 11498,
  'token_str': 'amor',
  'sequence': 'Yo tengo un amor que me ama'},
 {'score': 0.13567939400672913,
  'token': 46491,
  'token_str': 'hombre',
  'sequence': 'Yo tengo un hombre que me ama'},
 {'score': 0.08746496587991714,
  'token': 64536,
  'token_str': 'corazón',
  'sequence': 'Yo tengo un corazón que me ama'},
 {'score': 0.07230770587921143,
  'token': 38260,
  'token_str': 'amigo',
  'sequence': 'Yo tengo un amigo que me ama'},
 {'score': 0.05718352645635605,
  'token': 100426,
  'token_str': 'hijo',
  'sequence': 'Yo tengo un hijo que me ama'}]

In [55]:
pregyresp= pipeline(
    'question-answering', 
    model='mrm8488/distill-bert-base-spanish-wwm-cased-finetuned-spa-squad2-es',
    tokenizer=(
        'mrm8488/distill-bert-base-spanish-wwm-cased-finetuned-spa-squad2-es',  
        {"use_fast": False}
    )
)

In [58]:
pregyresp(
    {
        'question': '¿A dónde voy?',
        'context': 'Quiero ir de Cartagena a mi amada Bogotá'
    }
)

{'score': 0.8706352710723877, 'start': 34, 'end': 39, 'answer': 'Bogotá'}

In [57]:
pregyresp(
    {
        'question': '¿Quien comió?',
        'context': 'El perro se tragó la comida de mi hermano'
    }
)

{'score': 0.48023521900177, 'start': 31, 'end': 40, 'answer': 'mi hermano'}

In [59]:
pregyresp(
    {
        'question': '¿Quien comió?',
        'context': 'Mi hermano se tragó la comida del perro'
    }
)

{'score': 0.3061676323413849, 'start': 34, 'end': 38, 'answer': 'perro'}